SelfKeyFoundation/Identity-Wallet

app/src/angular/directives/commons/sk-id-attribute.directive.js, app/src/templates/common/dialogs/password-warning.pug, app/src/templates/common/dialogs/send-token.pug, app/src/templates/common/dialogs/startup-guide.pug, app/src/templates/guest/create/step-1.pug, app/src/templates/guest/create/step-3.pug, app/src/templates/guest/create/step-4.pug, app/src/templates/guest/create/step-5.pug, app/src/templates/guest/import/layout.pug, app/src/templates/guest/welcome.pug, app/src/templates/member/layout.pug, app/src/templates/member/setup/checklist.pug
Here are all screens: https://kyc-chain.atlassian.net/wiki/spaces/IDWAL/pages/43810971/UI+Changes
Numbers need to be done: 1, 2,  5, 6
=> Idwal00 s 18

package.json, src/main/autoupdater.js, src/main/controllers/sql-lite-service.js, src/renderer/angular/classes/wallet.js, src/renderer/angular/configs/app.run.js, src/renderer/angular/controllers/commons/dialogs/send-token-controller.js
This PR contains fixes for sending eth, key and custom tokens.
It specifically fixing the issue where after a transaction is sent the get transaction count does not return the count with the recent transaction sent. So I added a retry until it gets the right count to then create a new signed transaction.
Cheers
=> Fix sending eth, key and custom token

src/renderer/templates/common/dialogs/unlock-ledger-info.pug
Fix small typo and ledger button
=> fix: ledger try again typo

package.json, src/main/controllers/models/token-price.js, src/main/controllers/price-service.js, yarn.lock
Remove the interval for updating price and implement real time stream price update
=> feat: price real time update

package.json, test/config/config.js, test/test.js, test/unit/models/country.js
Add distinction between e2e and unit tests and setup basic unit tests
=> feat(tests): add basic unit test

src/renderer/angular/classes/wallet.js, src/renderer/angular/controllers/commons/dialogs/terms-controller.js, src/renderer/angular/directives/commons/scroll-to-end.directive.js
Not tested it on a customer yet
=> fix(terms): fix scroll to bottom not triggering in some cases

src/main/models/id-attribute.js, src/main/models/token-price.js, src/main/models/wallet.js
=> fix(walet-import): fix errors while importing old wallet

src/main/models/tx-history.js, test/unit/models/tx-history.spec.js
=> fix(tx-history): fix addOrUpdate model method

README.md
#267 add https://david-dm.org/SelfKeyFoundation/Identity-Wallet badge
=> feat(audit): add david status badge

package.json, src/common/logger.js, src/main/main.js, src/renderer/index.js
Setting up basic logging  for #269
=> feat(logger): setup logger

src/main/controllers/rpc-handler.js, src/main/models/tx-history.js, yarn.lock
=> fix(tx-history): circular dependency between model and service

src/common/logger/logger.js, src/main/models/__tests__/wallet-token.spec.js, src/main/models/wallet-token.js, src/renderer/angular/controllers/commons/dialogs/add-custom-token-controller.js
=> fix(wallet-token): fix add custom token

package.json, src/renderer/angular/services/rpc.service.js, src/renderer/angular/services/sql-lite.service.js, src/renderer/react/my-crypto/containers/crypto-price-table.js, yarn.lock
=> fix(price-table): visibility buttons

src/main/blockchain/web3-service.js, src/main/preload.js, src/main/rpc-handler.js, src/renderer/angular/controllers/commons/dialogs/send-token-controller.js, src/renderer/index.js, src/renderer/react/transaction/transaction-no-gas-error/containers/transaction-no-gas-error.js, src/renderer/react/transaction/transaction-no-gas-error/index.js, src/renderer/templates/common/dialogs/send-token.pug, yarn.lock
=> fix: not enough gas error message

package.json, src/main/blockchain/leadger-service.js, src/main/blockchain/leadger-service.spec.js, src/main/blockchain/tx-history-service.js, src/main/blockchain/tx-history-service.spec.js, src/main/composition-root.js, src/main/context.js, src/main/main.js, src/main/rpc-handler.js, yarn.lock
=> feat(di): introduce di and use it for services

src/main/blockchain/tx-history-service.js, src/main/blockchain/tx-history.js
related to #382 
Not a real fix since I could not reproduce. Just fixed some bugs. We'll see if it helps after release.
=> fix(tx-history): fix bugs

src/renderer/angular/configs/app.states.js, src/renderer/angular/controllers/member/marketplace/marketplace-controller.js, src/renderer/index.js, src/renderer/react/marketplace/index.js, src/renderer/templates/member/layout.pug, src/renderer/templates/member/marketplace/marketplace.pug, yarn.lock
This is just a first step towards the creating of the new marketplace as you can see it is hardcoded the data that goes to the screen. It will be taken from an airtable on the next release.
=> feat: add marketplace screen

src/main/lws/lws-service.js
add origin of chrome extension in production
=> feat(lws): add prod lws ext origin

yarn.lock
@andregoncalves I had to recreate the yarn.lock so to fix the build. Please review. cheers
=> fix: build

src/renderer/wallet/main/index.jsx
Remove static routes for the transfer main component.
=> fix: replace transfer funds static routes

src/renderer/wallet/create/backup-address.jsx, src/renderer/wallet/create/backup-pk.jsx, src/renderer/wallet/create/index.jsx, src/renderer/wallet/create/password/confirmation.jsx, src/renderer/wallet/create/password/index.jsx, src/renderer/wallet/create/password/password-util.js
* Changed color of button in Password Warning modal
* Modified style of Password strong checker (4 bars) and style of the text below
* Changed color of continue button in Step 3 modal
* Changed color of continue button in Step 4 modal
=> Fix - wallet setup

src/common/kyc/index.js, src/main/platform/relying-party.js, src/main/platform/relying-party.spec.js
+ update attribute structure on create Application
+ add update Application endpoint to relying party
=> feat(kyc-api): update kyc api client

src/renderer/marketplace/incorporation/pay/payment-confirmation-content.jsx
- alignment and style of components
=> fix: alignment and style of UI elements

src/common/identity/selectors.js, src/common/kyc/index.js, src/renderer/kyc/index.js, src/renderer/kyc/kyc-manager.jsx, src/renderer/kyc/requirements/container.jsx, src/renderer/kyc/requirements/requirements-list.jsx
+ add kyc manager component (list of kyc requirements for now)
+ add kyc requirements component
=> feat(kyc-requirements): add kyc manager and requirements components

src/renderer/address-book/add/index.jsx, src/renderer/address-book/edit/index.jsx, src/renderer/address-book/main/index.jsx
*  Changed alignment of Address Book screen and fixed table
*  Changed alignment of Add/Edit Address modals and Font size of buttons
=> Address Book UI fixes

src/renderer/wallet/main/toolbar.jsx
- Fixed this funky alignment issue
- Changed style of vertical divider
=> Fix - Header

src/common/app/index.js, src/renderer/wallet/unlock/new-address.jsx, yarn.lock
+ disable unlock button when no file selected
+ disable unlock button when password empty
+ display file path to indicate file is selected
+ transform error message 'Key derivation failed - possibly wrong password' -> 'Wrong password. Please try again'
=> fix(new-address): disable submit button when needed

package.json, webpack/main.additions.js, webpack/renderer.additions.js, yarn.lock
remove harsource plugin until https://github.com/mzgoddard/hard-source-webpack-plugin/issues/481 is fixed
=> fix(hardsource): remove hardsource plugin

src/renderer/dashboard/index.jsx, src/renderer/kyc/application/current-application-container.jsx, src/renderer/kyc/application/current-application-popup.jsx
+ agreement error and submit disable
+ invalid attribute error and submit disable
+ check if all attributes are valid before submit
+ check if there are missing attributes before submit
+ apply warning styles to invalid attributes
=> feat(kyc-application): error handlers

src/renderer/marketplace/incorporation/detail/components/legal-view.jsx
Legal tab was displaying data not relevant to LLCs.
This fix corrects that.
=> fix: better support for LLCs in legal tab

package.json, yarn.lock
related to:
https://github.com/SelfKeyFoundation/selfkey-ui/pull/93
https://github.com/SelfKeyFoundation/react-jsonschema-form-material-theme/pull/10
=> feat(attributes): fix date

src/renderer/marketplace/incorporation/detail/index.jsx
=> fix: list styling of incoming airtable html data, #749

src/renderer/marketplace/incorporation/common/kyc-requirements.jsx, src/renderer/marketplace/incorporation/detail/index.jsx
Prevent incorporation details screen from crashing if kyc-chain connection has issues
=> fix: checks for template existence and valid kyc relying party

src/renderer/wallet/create/index.jsx, src/renderer/wallet/create/password/confirmation.jsx, src/renderer/wallet/create/password/index.jsx, src/renderer/wallet/unlock/index.jsx
Fixed position of Close Icon in different screens 
- Use an Existing ETH Address
- Create New Screens
=> fix: modified position of Close Icon

src/renderer/marketplace/incorporation/common/kyc-requirements.jsx
=> fix: alignment of KYC Requirements and Forms list

src/renderer/marketplace/incorporation/pay/process-started.jsx
https://github.com/SelfKeyFoundation/Identity-Wallet/issues/792#issuecomment-469357013
=> fix: modified flagtheory support email address

src/renderer/selfkey-id/main/components/selfkey-id-overview.jsx
=> fix: issue #803, white space in muiTableCell

src/renderer/kyc/application/current-application-popup.jsx
=> fix: issue #806, white space in muiTableCell

package.json, static/stylesheets/scss/variables.scss, webpack/dll.additions.js, webpack/main.additions.js, yarn.lock
Reverts SelfKeyFoundation/Identity-Wallet#817
=> Revert "Revert "Fix/harsource""

src/renderer/selfkey-id/main/components/selfkey-id-overview.jsx
Added missing classes for fixing issue #803
=> fix: added class for removing white-space behavior

src/renderer/kyc/application/current-application-popup.jsx, src/renderer/selfkey-id/main/components/selfkey-id-overview.jsx
Css fixes for issues #840 #806 and #803
=> fix: break-word and css fixes - #840 #806 #803

src/renderer/marketplace/incorporation/table/index.jsx
Fixes issue with material-ui fixed row height in incorporations marketplace table #805
=> fix: issue with row height - #805

package.json, yarn.lock
related to issue https://github.com/SelfKeyFoundation/Identity-Wallet/issues/853
=> feat(id-attributes): required symbol -> *

src/common/config.js, src/renderer/marketplace/incorporation/pay/checkout.jsx, src/renderer/marketplace/incorporation/pay/process-started.jsx
Wiring up of production FT data and kyc-chain instance to the wallet (#760)
=> FT production data and kyc-chain wire up

src/renderer/kyc/application/current-application-popup.jsx
add legal text to kyc checkbox #781
=> fix: add legal text to kyc checkbox #781

src/renderer/kyc/application/current-application-popup.jsx
=> fix: missing closing anchor tag

src/renderer/dashboard/crypto-chart-box.jsx, src/renderer/transaction/transactions-history/index.jsx
Changes
- Style of the Transactions table
- Fixed time format. There were missing 0s (under 10) in minutes and hours.
=> Fix- #970 transactions history

src/common/config.js, src/main/marketplace/incorporations-service.js, src/renderer/marketplace/incorporation/detail/index.jsx
- Incorporation Airtable schema changes
- Hardcoded incorporations API URLs moved out of service file to config (with the added ability to override them via env vars)
=> Incorporations schema changes and refactor

src/common/exchanges/selectors.js
Fixes error when exchanges logo is not available.
=> fix: logo url error when loading exchanges

src/renderer/deposit/transactions/without-balance-popup.jsx
Changes:
- Added title to Fix not enough key token modal
=> fix: added title to modal header

src/renderer/kyc/requirements/requirements-list.jsx, src/renderer/marketplace/incorporation/common/kyc-requirements.jsx
Changed: 
- removed Document Icon from KYC requirements in marketplace
https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1130
=> fix: removed Document Icon from KYC requirements

src/renderer/marketplace/services/service-details.jsx
Changes: 
- removed React truncate
- removed View Details/Collapse all buttons
from Exchanges detail screen
=> fix: removed react truncate and view all details button

src/renderer/selfkey-id/main/components/selfkey-id-overview.jsx
Changes: 
- Changed text and alignment of Processing transaction
`release branch`
Final result:
=> fix: alignment of Processing transaction text

src/renderer/marketplace/bank-accounts/list/offers-table.jsx
=> fix: broken eligibility table cell

.gitignore, src/renderer/marketplace/bank-accounts/details/account-option.jsx, src/renderer/marketplace/bank-accounts/details/option-selection.jsx, stories/banking.stories.js
=> feat(bam): create choose bank option

src/renderer/marketplace/incorporation/pay/payment-confirmation.jsx
=> fix: typo on Incorporations Payment Confirmation

src/common/identity/utils.js, src/renderer/selfkey-id/main/components/create-attribute.jsx, src/renderer/selfkey-id/main/components/edit-attribute.jsx
fix for #1293
I've added a new validation on create/edit attribute form, it will prevent users from uploading empty files.
=> fix: add validation for empty files

src/main/marketplace/bank-accounts-service.js, src/main/marketplace/incorporations-service.js, src/renderer/marketplace/bank-accounts/list/offers-container.jsx, src/renderer/marketplace/incorporation/table/index.jsx, src/renderer/no-connection/index.jsx
=> fix: correct loading handling for marketplaces

src/renderer/kyc/application/application-status.jsx, src/renderer/marketplace/bank-accounts/checkout/checkout-container.jsx, src/renderer/marketplace/bank-accounts/details/details-container.jsx, src/renderer/marketplace/bank-accounts/details/details-page.jsx, src/renderer/marketplace/bank-accounts/index.jsx, stories/kyc.stories.js
=> feat: display application status

src/renderer/dashboard/crypto-chart-box.jsx
Added arrow to Tooltip component.
Result:
=> fix: added arrow to Tooltip

src/renderer/marketplace/categories/category.jsx
Changes:
- Decreased button font size
- `Learn more` button label to `Access marketplace`
https://projects.invisionapp.com/d/main#/console/15222689/318479882/preview
=> fix: changed size and text of buttons

src/renderer/marketplace/bank-accounts/common/account-option.jsx
Fixed breaking layout in smaller screen
=> fix: alignment of Banking Account options

src/renderer/marketplace/bank-accounts/common/account-option.jsx
Issue:
Fix (Sanitize and renders html):
=> fix: html in bank details tab

src/common/config.js
=> refactor: change FT KYCC test instance

package.json, yarn.lock
Changes:
https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1337
=> feat: updated Selfkey UI

src/renderer/selfkey-id/main/components/selfkey-id-overview.jsx
Changes: 
- increased size of buttons
- reduced big spacing between buttons
=> fix: changed style of DID buttons

src/renderer/dashboard/crypto-chart-box.jsx
Changes: 
- back to html styled tooltip
- deleted arrow
=> fix: back to html styled tooltip without arrow

package.json, src/renderer/marketplace/bank-accounts/list/offers-table.jsx, src/renderer/marketplace/common/program-price.jsx, src/renderer/marketplace/incorporation/table/index.jsx, src/renderer/marketplace/services/services-list-item.jsx, yarn.lock
Changes:
https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1364
=> fix: table alignments

src/common/kyc/index.js
=> fix(manage-application): add descending order sort

src/renderer/selfkey-id/main/components/selfkey-id-applications.jsx
=> feat(manage-applications): additional requirements redirect to KYCC

src/renderer/selfkey-id/main/components/selfkey-id-applications.jsx
=> fix(manage-applications): update loading flag

src/renderer/selfkey-id/main/components/selfkey-id-applications.jsx
=> fix(manage-applications): update rpName and messages

src/common/marketplaces/orders/index.js, src/renderer/marketplace/bank-accounts/checkout/payment-container.jsx, src/renderer/marketplace/orders/payment-container.jsx, src/renderer/marketplace/orders/tx-error-container.jsx
Refactor contract amount to own selector.
Fix problem when allowance is too large (53bit issue)
Fiat rate  needs to be in 'KEY'
=> refactor: payment amount

src/renderer/no-connection/index.jsx
=> fix(no-connection): add default back to dashboard redirect

src/renderer/marketplace/bank-accounts/common/account-option.jsx
=> fix: correct typo and missing prop

src/renderer/no-connection/index.jsx
=> fix(no-application): change to close the wallet

src/common/config.js, src/common/marketplaces/orders/index.js, src/common/transaction/operations.js, src/common/transaction/types.js, src/main/marketplace/orders/order.js, src/main/migrations/20190716114307_add_wallet_to_orders.js, src/renderer/marketplace/bank-accounts/checkout/payment-container.jsx, src/renderer/marketplace/orders/payment-container.jsx, src/renderer/marketplace/orders/payment.jsx, src/renderer/no-connection/index.jsx, yarn.lock
Integration of direct wallet-to-wallet payments in marketplace orders (bypass paymentContract feature)
=> feat: BAM direct wallet payments

src/renderer/marketplace/bank-accounts/details/details-tabs.jsx
=> fix: incorrect tab value

src/common/kyc/index.js, src/renderer/selfkey-id/main/components/selfkey-id-applications.jsx
=> fix(manage-applications): workaround for payment and title

.circleci/config.yml, src/common/exchanges/selectors.js, src/common/scheduler/index.js, src/renderer/marketplace/incorporation/index.jsx
Link exchanges to scheduler store.
Using feature flag to keep old functionality.
=> feat: link exchanges to scheduler store

src/common/config.js, src/common/exchanges/selectors.js
Activate scheduler feature flag on prod.
=> fix: update scheduler feature flag

stories/banking-data.js, stories/banking.stories.js
Fixes issues in storybook caused by marketplace refactoring
=> fix: invalid banking story data

src/renderer/wallet/main/sidebar.jsx
=> feat: add title to all icons in Sidebar

src/renderer/corporate/common/corporate-information.jsx, stories/corporate.stories.js
=> feat: add missing buttons and actions to corporate informations component

src/renderer/corporate/common/corporate-documents.jsx, stories/corporate-data.js, stories/corporate.stories.js
=> feat: corporate documents componenent

src/renderer/wallet/main/toolbar.jsx
Remove the "new corporate" button in the UI if corporate feature flag is disabled.
=> feat: disabled new corp button if corp is disabled

src/common/kyc/index.js, src/common/marketplace/vendors/index.js, src/main/kyc/kyc-application-service.js, src/renderer/selfkey-id/main/components/selfkey-id-applications.jsx, src/renderer/selfkey-id/main/containers/selfkey-id-applications.js, src/renderer/selfkey-id/main/containers/selfkey-id.js
Basic functionality, still needs further work in the future.
=> fix: refactor manage applications for store integration

src/renderer/marketplace/bank-accounts/checkout/checkout-container.jsx, src/renderer/marketplace/bank-accounts/checkout/payment-complete-container.jsx, src/renderer/marketplace/bank-accounts/checkout/payment-container.jsx, src/renderer/marketplace/incorporation/checkout/incorporations-checkout-container.jsx, src/renderer/marketplace/incorporation/checkout/incorporations-payment-complete-container.jsx, src/renderer/marketplace/incorporation/checkout/incorporations-payment-container.jsx, src/renderer/marketplace/incorporation/details/incorporations-details-container.jsx
Some props were missing on my earlier refactoring of marketplace components.
Related to #1602
=> fix: and refactor missing props in marketplace components

src/renderer/corporate/common/corporate-details.jsx, src/renderer/corporate/common/corporate-information.jsx, src/renderer/corporate/dashboard/dashboard-page.jsx, src/renderer/corporate/dashboard/overview-tab.jsx
- Fixes issue when displaying object type attributes in the informations & documents tab
- Fixes issue with displaying address attribute in the overview details block
- Links overview edit action to the informations & documents tab
=> fix: object type attributes

src/common/config.js
=> feat: certifiers feature flag

package.json, src/renderer/corporate/common/corporate-applications.jsx, src/renderer/corporate/common/corporate-cap-table.jsx, src/renderer/corporate/common/corporate-details.jsx, src/renderer/corporate/common/corporate-documents.jsx, src/renderer/corporate/common/corporate-information.jsx, src/renderer/corporate/common/corporate-org-chart.jsx, src/renderer/corporate/common/corporate-shareholding.jsx, src/renderer/corporate/dashboard/dashboard-page.jsx, src/renderer/corporate/dashboard/dashboard-tabs.jsx, src/renderer/corporate/dashboard/overview-tab.jsx, src/renderer/corporate/wizard/corporate-wizard.jsx, src/renderer/did/register-did-card.jsx, yarn.lock
Fixed the following issues and removed unnecessary Grids from some screens.
1. Corporate Wallet Setup - please change the tittle to Wallet instead of Vault
2. Corporate Wallet Setup - Continue button should be left aligned with the box above
3. Corporate Wallet Setup - please follow the spacing from Invision, paddings inside the box, and vertical spacing of elements
4. Date picker - months names should be centered https://gyazo.com/8848a58a617d05ad8c5560ed1c6334a9
5. Corporate wallet Dashboard - please change the tittle to Wallet instead of Vault
6. Corporate wallet Dashboard - fix vertical spacing of tabs and spacing between boxes
7. Corporate wallet Dashboard - Company, application status, cap table, and the rest of the boxes - make sure the elements don’t overflow the box padding …
=> Fix/1649 corporate wallet UI

src/renderer/marketplace/bank-accounts/list/offers-container.jsx
=> Order bank offers alphabetically

src/renderer/marketplace/exchanges/exchanges-details-container.jsx, src/renderer/marketplace/exchanges/exchanges-details.jsx
Affiliate signup button for exchanges. #1573
=> feat: affiliate link for exchanges

scripts/notarize.js
Need to update appid password on circle ci before release
=> HOTFIX -- notarize for Catalina v1.4.1

src/renderer/dashboard/token-box.jsx
=> fix: short address in Tokenbox

src/renderer/marketplace/exchanges/exchanges-details.jsx, yarn.lock
=> feat: add affiliate disclaimer below signup button

src/common/marketplace/countries/index.js, src/main/marketplace/countries/marketplace-country-service.js, src/main/marketplace/inventory/inventory-service.js, src/renderer/marketplace/bank-accounts/list/offers-container.jsx
- Fix: no longer display offers with zero bank accounts (airtable data is dynamic)
- Fix: remove possible airtable data empty spaces in key linking columns
Fixes issue #1749
=> fix: errors on BAM data binding and select

src/renderer/corporate/common/corporate-details.jsx
=> fix: corp address missing bug

src/renderer/corporate/common/corporate-information.jsx
=> fix: show label instead of value

src/main/marketplace/inventory/inventory-sync-job-handler.js
Inventory should be removed if vendor is removed. #1785
=> fix: handle missing vendor in inventory sync

src/renderer/marketplace/exchanges/exchanges-details.jsx
=> fix: capitalize disclaimer message

src/renderer/corporate/common/corporate-shareholding.jsx, stories/corporate-data.js, stories/corporate.stories.js
=> feat: adjust corporate shareholding graph to the new members structure

stories/notarization.stories.js
Changes:
- Added Notarization realated Containers to Storybook
=> feat: notarization storybook

src/common/identity/constants.js, src/common/identity/index.js, src/common/identity/memoazed-selectors.js, src/common/identity/memoized-selectors.js, src/common/identity/selectors.js, src/common/identity/utils.js, src/renderer/selfkey-id/main/containers/selfkey-id.js
=> feat(memoize): memoize identity selectors

src/renderer/kyc/application/current-application-popup.jsx
Changes:
- Center aligned table elements
https://gyazo.com/57c50bfe7428a2f6b12a17c576a634b2
=> fix: alignment of Current Application popup table

src/renderer/transaction/common/transaction-error-box.jsx, src/renderer/transaction/transaction-no-key-error/components/transaction-no-key-error.jsx
Changes:
https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1830
=> fix: style and alignment of Error popup

src/renderer/selfkey-id/main/components/selfkey-id.jsx
Changed the title of the page to `Selfkey Profile`
=> fix: title of SK ID page

src/renderer/wallet/main/sidebar.jsx
Changes:
https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1827
=> fix: added hover title to list items

src/renderer/kyc/application/current-application-popup.jsx
Changes:
- Alignment of label cells
=> fix: alignment of label cells

src/renderer/marketplace/notarization/details/notarization-details-page.jsx, stories/notarization.stories.js
Changes:
- Removed static data from `NotarizationDetailsPage` component
=> fix: removed static data from component

src/common/identity/operations.js
=> fix: error in selection of attributes for editing instead of creating

src/common/identity/__fixtures__/corporate-structure-schema.js, src/common/identity/corporate-structure-schema.js, src/common/identity/corporate-structure-schema.spec.js, src/common/identity/selectors.js, src/renderer/corporate/common/common-helpers.jsx, src/renderer/corporate/member/corporate-member-container.jsx, src/renderer/corporate/member/corporate-member-form.jsx, src/renderer/corporate/member/member-shares-form.jsx
=> feat: add equity validation based on position

src/common/identity/constants.js, src/common/identity/operations.js, src/common/identity/selectors.js, src/renderer/corporate/member/corporate-member-container.jsx, src/renderer/corporate/member/corporate-member-form.jsx, src/renderer/corporate/member/member-select-role.jsx
* Fix wrong required attributes
* Move attribute required checking to before identity creation
* Validate empty member position
=> fix: improved member validation and creation

package.json, yarn.lock
Changes: 
https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1894
=> Backdrop opacity

src/renderer/marketplace/bank-accounts/checkout/payment-complete.jsx
Changes:
- style of the popup (shadow, font size, padding, width)
=> fix: alignment and style of BAM payment complete popup

package.json, yarn.lock
Changes: 
https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1901
=> feat: updated SK UI

src/renderer/corporate/common/corporate-shareholding.jsx
=> feat(shareholders): fix unassigned in shareholders graph

src/renderer/corporate/wizard/corporate-wizard-container.jsx
Changed so that initial state is empty.
=> Fix/1908 don't pre-fill attributes on company creation

src/renderer/corporate/common/corporate-edit-form.jsx, src/renderer/corporate/member/member-corporate-form.jsx, src/renderer/corporate/wizard/corporate-wizard.jsx
=> fix: missing placeholder

src/renderer/corporate/common/corporate-information.jsx, src/renderer/corporate/dashboard/dashboard-container.jsx
Fixes #1984 
Also fixes issue with external document title.
=> fix: attributes for corporate info

src/main/marketplace/vendors/vendor.js, src/main/migrations/20200108094700_clean_terms_of_service.js, src/renderer/marketplace/incorporation/details/incorporations-details-description-tab.jsx
- Adds missing termsOfService vendor column.
- Cleans up local database.
- Removes stray log file
=> fix: missing terms and conditions, clean up column

src/renderer/marketplace/bank-accounts/checkout/checkout-container.jsx, src/renderer/marketplace/bank-accounts/details/details-container.jsx, src/renderer/marketplace/incorporation/checkout/incorporations-checkout-container.jsx, src/renderer/marketplace/incorporation/details/incorporations-details-container.jsx
#1971 - moves KEY not available popup to the checkout page
=> feat: improve no key flow, moved check to checkout page

src/renderer/corporate/dashboard/overview-tab.jsx
Changes:
Fixed this issue 
https://gyazo.com/63944f70ecf536f04b7881eabebc4b39
=> fix: alignment of corporate shareholding

src/renderer/corporate/common/corporate-cap-table.jsx, src/renderer/corporate/common/corporate-members.jsx, src/renderer/corporate/common/corporate-shareholding.jsx
=> fix: add % to shares, improve chart tooltip

src/common/identity/operations.js, src/renderer/app.jsx, src/renderer/individual/dashboard/dashboard-container.jsx, src/renderer/selfkey-id/main/containers/selfkey-id.js
#1223 - remove page from selfkey identity creation flow
=> feat: remove setup your selfkey identity page

src/main/platform/relying-party.js, src/renderer/kyc/application/current-application-container.jsx, src/renderer/kyc/application/current-application-popup.jsx
=> fix: 2031 - optional kyc requirements are no longer mandatory

src/common/identity/operations.js, src/renderer/app.jsx, src/renderer/individual/dashboard/dashboard-container.jsx
=> feat: remove about and what are attributes screens

src/renderer/crypto-manager/crypto-price-table.jsx
Changes: 
https://github.com/SelfKeyFoundation/Identity-Wallet/issues/1861
=> fix: added currency to token price table

src/main/marketplace/inventory/inventory-service.js
Connect loans airtable endpoint to scheduler
=> feat: add loans airtable to scheduler

src/renderer/transaction/send/advanced-transaction.jsx
Changes:
- Added placeholder to Send/Receive token modal
=> fix: added placeholder to Token selector

src/renderer/wallet/unlock/select-address.jsx
Changes:
- Fixed alignment of address table
=> fix: alignment of ledger table

src/renderer/wallet/main/toolbar.jsx
Changes:
https://github.com/SelfKeyFoundation/Identity-Wallet/issues/2048
=> fix: visibility of toolbar

src/renderer/transaction/transactions-history/index.jsx
Changes:
- Removed hourglass icon and added disable state to refresh icon
=> fix: added disable state to refresh icon

src/renderer/marketplace/bank-accounts/details/details-country-tab.jsx, src/renderer/marketplace/bank-accounts/details/details-description-tab.jsx, src/renderer/marketplace/bank-accounts/details/details-services-tab.jsx, src/renderer/marketplace/bank-accounts/details/details-types-tab.jsx, src/renderer/marketplace/common/marketplace-what-you-get.jsx, src/renderer/marketplace/common/what-you-get-tab.jsx, src/renderer/marketplace/incorporation/details/incorporations-details-country-tab.jsx, src/renderer/marketplace/incorporation/details/incorporations-details-description-tab.jsx, src/renderer/marketplace/incorporation/details/incorporations-details-legal-tab.jsx, src/renderer/marketplace/incorporation/details/incorporations-details-services-tab.jsx, src/renderer/marketplace/incorporation/details/incorporations-details-tax-treaties-tab.jsx, src/renderer/marketplace/incorporation/details/incorporations-details-taxes-tab.jsx
Changes:
- removed `border-bottom` property from `strong` tag
=> fix: removed border bottom from strong tag

.circleci/config.yml, .circleci/ignore-storybook.yml
get built storybook from workspace
=> fix: storybook build

src/renderer/dashboard/buy-key-popup-modal.jsx
Changes:
https://gyazo.com/e3b1ecb3ad5615946a0bd2c7b336c7b4
=> fix: alignment of elements in Buy Key modal

src/renderer/marketplace/loans/calculator/borrow-table.jsx, src/renderer/marketplace/loans/calculator/lend-table.jsx, src/renderer/marketplace/loans/common/filters.jsx, src/renderer/marketplace/loans/common/table.jsx
=> fix: removes default loan type, renames Decentralized with P2P

src/renderer/marketplace/loans/calculator/index.jsx, src/renderer/marketplace/loans/common/filters.jsx, src/renderer/marketplace/loans/common/marketplace-loans-component.jsx, src/renderer/marketplace/loans/common/table.jsx, src/renderer/marketplace/loans/list/list-page.jsx
- Fixes storybook issue
- Addresses issues described here: https://github.com/SelfKeyFoundation/Identity-Wallet/issues/2198#issuecomment-623997618
=> fix: misc loan marketplace fixes

src/common/token-swap/index.js, src/renderer/transaction/swap/index.jsx
- Fixes token address selection problem
- Layout issue with max swap info
=> fix: layout fixes, token selection fixes

src/renderer/corporate/member/member-corporate-form.jsx, src/renderer/corporate/member/member-individual-form.jsx, src/renderer/corporate/wizard/corporate-wizard.jsx, src/renderer/marketplace/loans/common/filters.jsx, src/renderer/transaction/send/advanced-transaction.jsx, src/renderer/transaction/transactions-history-modal/index.jsx, src/renderer/wallet/unlock/existing-address.jsx
Need to update this PR with latest Selfkey UI after the following PR will be merged https://github.com/SelfKeyFoundation/selfkey-ui/pull/206
Changes:
https://github.com/SelfKeyFoundation/Identity-Wallet/issues/2165#issue-598783590
=> fix: changed dropdown icon and style of Choose text

package.json, yarn.lock
Changes:
- updated Wallet with new style of `Copy` button
=> 2033 copy button

src/renderer/settings/terms.jsx
Text fixes to terms described in #2185
=> 2185 terms fixes

src/renderer/marketplace/loans/calculator/borrow-table.jsx, src/renderer/marketplace/loans/calculator/index.jsx, src/renderer/marketplace/loans/calculator/lend-table.jsx, src/renderer/marketplace/loans/common/table.jsx, src/renderer/marketplace/loans/details/details-highlights.jsx, src/renderer/marketplace/loans/details/details-requirements.jsx, src/renderer/marketplace/loans/list/tabs.jsx
Addresses some of the issues described here #2198:
- loans provider logo styling
- loans table cell styling
- correct calculator my crypto placeholder
- missing calculator container
- replace maximum text with max in loans provider details view
- fix text alignment and margins in requirements section
=> 2198 loans marketplace visual fixes

src/renderer/marketplace/exchanges/exchanges-list-item.jsx, src/renderer/marketplace/exchanges/exchanges-list.jsx
Changes:
https://github.com/SelfKeyFoundation/Identity-Wallet/issues/2215#issuecomment-630159522
=> fix: width of excluded residents table cell

src/renderer/transaction/send/advanced-transaction.jsx
Changes:
https://github.com/SelfKeyFoundation/Identity-Wallet/issues/2056
=> fix: amount input and updated default amount after token changing

package.json, src/renderer/dashboard/buy-key-widget.jsx, src/renderer/marketplace/common/resume-box.jsx, yarn.lock
Changes:
https://github.com/SelfKeyFoundation/Identity-Wallet/issues/2166
=> 2166 small ui fixes

src/renderer/marketplace/loans/calculator/index.jsx
Addresses issues with calculator formulas #2198
=> 2198 fix loan calculator formulas

src/renderer/marketplace/bank-accounts/details/details-country-tab.jsx, src/renderer/marketplace/bank-accounts/details/details-description-tab.jsx, src/renderer/marketplace/bank-accounts/details/details-services-tab.jsx, src/renderer/marketplace/bank-accounts/details/details-types-tab.jsx, src/renderer/marketplace/common/sanitize-airtable-html.js, src/renderer/marketplace/incorporation/details/incorporations-details-country-tab.jsx, src/renderer/marketplace/incorporation/details/incorporations-details-description-tab.jsx, src/renderer/marketplace/incorporation/details/incorporations-details-legal-tab.jsx, src/renderer/marketplace/incorporation/details/incorporations-details-services-tab.jsx, src/renderer/marketplace/incorporation/details/incorporations-details-tax-treaties-tab.jsx, src/renderer/marketplace/incorporation/details/incorporations-details-taxes-tab.jsx
Changes:
- https://github.com/SelfKeyFoundation/Identity-Wallet/issues/2003#issue-550051803
- and fixed line height of `Services` tab in Bank Account Marketplace (before and after)
=> 2003 marketplace description

package.json, src/renderer/marketplace/bank-accounts/common/details-button.jsx, yarn.lock
Changes:
- standardise Details button in Marketplace tables
=> 2004 ui details link

src/renderer/individual/dashboard/applications-tab.jsx, src/renderer/selfkey-id/main/components/selfkey-id-applications.jsx
Changes:
- refactored HeaderIcon
=> 2032 headericon

src/renderer/marketplace/loans/calculator/borrow-table.jsx, src/renderer/marketplace/loans/calculator/index.jsx, src/renderer/marketplace/loans/calculator/lend-table.jsx, src/renderer/marketplace/loans/common/table.jsx
Changes:
https://github.com/SelfKeyFoundation/Identity-Wallet/issues/2288#issue-629057334 and
- fixed font sizes
- handled long names in table
=> 2288 loans calculator table

src/renderer/marketplace/exchanges/exchanges-details.jsx, src/renderer/marketplace/loans/details/details.jsx
=> fix: add right margin to loans and exchanges provider description

src/renderer/marketplace/exchanges/exchanges-details.jsx, src/renderer/marketplace/loans/details/details.jsx
Changes:
- standardised padding in Exchanges and Loans description pages
=> fix: padding in Exchange and Loan details pages

package.json, src/renderer/marketplace/loans/calculator/index.jsx, src/renderer/marketplace/loans/common/filters.jsx, src/renderer/marketplace/loans/common/table.jsx, yarn.lock
Fixes button groups in loans calculator and listing. #2277
=> fix: button groups in loans calculator

src/renderer/corporate/member/member-corporate-form.jsx, src/renderer/corporate/member/member-individual-form.jsx, src/renderer/corporate/member/member-shares-form.jsx, src/renderer/corporate/wizard/corporate-wizard.jsx
Changes:
- changed locally defined component to common `InputTitle` component
=> fix: use InputTitle common component

src/renderer/corporate/wizard/corporate-wizard.jsx
=> fix: position of dropdown icon

package.json, src/renderer/common/alert.js, src/renderer/marketplace/common/marketplace-how-service-works.jsx, src/renderer/transaction/send/containers/receive-token-tab.jsx, yarn.lock
Changes:
- updated Wallet with the latest Selfkey UI changes (removed jss)
- removed react jss in `receive-token-tab`
- fixed size of `how it works` boxes in `marketplace-how-service-works`
=> 2297 remove jss

src/renderer/address-book/main/index.jsx
Addresses issue when loading address book from marketplace pages.
=> 2317 fix addressbook routing

src/renderer/dashboard/crypto-chart-box.jsx
ETH and KEY colors for dashboard chart
=> 2319 check for eth and key in chart colors

src/renderer/common/alert.js
Changes:
- added `border-radius` to Alert component
=> fix: added border radius to Alert

src/renderer/marketplace/notarization/common/toc-disagreement-popup.jsx, src/renderer/marketplace/notarization/common/toc-popup.jsx
Changes: 
- Removed old version of box shadow and 
- Started to use Popup components for modals
=> 2322 fix notarization popups

package.json
=> Release 1.6.4

package.json, yarn.lock
Changes:
- style of checkboxes
=> feat: updated with latest Selfkey UI

src/renderer/settings/terms.jsx
Changes:
- Size of popup window in different vertically breakpoints
=> fix: height of TOS in different window sizes

src/renderer/deposit/transactions/deposit-content.jsx, src/renderer/kyc/application/kyc-agreement.jsx
First I created wrong branch name, this is the https://github.com/SelfKeyFoundation/Identity-Wallet/issues/2341 issue. 
Changes:
- added missing error styling to checkboxes
=> 2342 checkbox error

src/renderer/common/alert.js, src/renderer/kyc/application/application-status.jsx, src/renderer/marketplace/bank-accounts/details/details-page.jsx, src/renderer/marketplace/incorporation/details/incorporations-details-page.jsx
Changes:
- Standardized `Application Statuses` styles with Alert component
=> 2328 fix alert comp

package.json, src/renderer/wallet/main/sidebar.jsx, yarn.lock
Changes:
- fixed size of `Selfkey logo` in Sidebar
=> 2350 selfkey logo

src/renderer/home/index.jsx, src/renderer/selfkey-id/main/components/selfkey-id-create-about.jsx, src/renderer/selfkey-id/main/components/selfkey-id-create-disclaimer.jsx, src/renderer/selfkey-id/main/components/selfkey-id-create.jsx, src/renderer/transaction/receive/index.jsx, src/renderer/transaction/send/index.jsx, src/renderer/wallet/create/backup-address.jsx, src/renderer/wallet/create/backup-pk.jsx, src/renderer/wallet/create/index.jsx, src/renderer/wallet/create/password/confirmation.jsx, src/renderer/wallet/create/password/index.jsx, src/renderer/wallet/main/sidebar.jsx, src/renderer/wallet/unlock/index.jsx
Changes:
- extended `Link` components with `ref` property -> fixed console warning. 
https://material-ui.com/guides/composition/#caveat-with-refs
=> fix: links

package.json, src/renderer/common/accordion.jsx, src/renderer/individual/dashboard/applications-tab.jsx, src/renderer/marketplace/bank-accounts/common/account-option.jsx, src/renderer/marketplace/notarization/details/notarization-details-types-tab.jsx, src/renderer/selfkey-id/main/components/selfkey-id-applications.jsx, src/renderer/selfkey-id/main/components/selfkey-id-companies.jsx, yarn.lock
Changes:
- updated latest Selfkey UI
- used new expand icons
- fixed position of expand icons
=> fix: changed expand icons

src/renderer/dashboard/dashboard-marketplace-applications.jsx
=> 2365 spacing around status

package.json, src/renderer/address-book/main/index.jsx, src/renderer/attributes/delete-attribute.jsx, src/renderer/corporate/member/corporate-member-form.jsx, src/renderer/did/register-did-card.jsx, src/renderer/individual/dashboard/overview-tab.jsx, src/renderer/marketplace/bank-accounts/common/account-option.jsx, src/renderer/marketplace/bank-accounts/details/details-page.jsx, src/renderer/marketplace/exchanges/exchanges-details.jsx, src/renderer/marketplace/incorporation/details/incorporations-details-page.jsx, src/renderer/marketplace/incorporation/list/incorporations-list-page.jsx, src/renderer/marketplace/loans/calculator/index.jsx, src/renderer/marketplace/loans/details/details.jsx, src/renderer/selfkey-id/main/components/selfkey-id-create.jsx, src/renderer/selfkey-id/main/components/selfkey-id-overview.jsx, src/renderer/transaction/swap/index.jsx, yarn.lock
Changes:
- fixed Materiel UI warnings
- mostly changed/removed wrong parameters in Grid tags
- changed some Typography variant value for existing one
=> 2371 fix material ui warnings

src/main/common/base-model.js, src/main/marketplace/inventory/inventory-service.js, src/main/marketplace/inventory/inventory-service.spec.js, src/main/marketplace/inventory/inventory-sync-job-handler.js, src/main/marketplace/inventory/inventory.js
if one of the synced inventory items fails, sync other items anyway
=> feat(inventory): continue sync after single upsert failure

src/renderer/dashboard/crypto-chart-box.jsx, yarn.lock
=> 2361 fix token graph colors

src/renderer/kyc/application/current-application-container.jsx
Fixes issue when closing KYC checklist, unwanted modal is displayed. http://recordit.co/rdmlgOiCWi.
=> fix: kyc requirements render flash when closing

src/main/menu.js
=> fix(about-screen): enable remote module to fetch version

src/renderer/selfkey-id/main/components/selfkey-id-create-form.jsx
Changes:
- position of Back Button (left aligned)
=> fix: position of Back button

src/renderer/crypto-manager/add-token.jsx
Changes:
- position of Back button
=> 2433 back button

src/renderer/crypto-manager/crypto-manager.jsx
Changes:
- position of Back Button (left aligned)
=> fix: alignment of back button

src/main/blockchain/tx-history.js
Prevent error transactions from continuously resyncing with blockchain.
=> fix: prevent error transactions from continously syncing

src/renderer/marketplace/keyfi/checkout/keyfi-checkout.jsx, stories/marketplace-common.stories.js
Storybook and styling fixes for keyfi views.
=> fix: missing storybook screens

src/renderer/kyc/application/current-application-container.jsx, src/renderer/kyc/application/current-application-popup.jsx, src/renderer/marketplace/keyfi/checkout/keyfi-checkout-container.jsx
=> 2457 Disable kyc button on submit

src/renderer/dashboard/buy-key-popup-modal.jsx
Changes:
- hover state to listing elements
=> fix: hover state to listing elements

src/renderer/individual/dashboard/applications-tab.jsx, src/renderer/kyc/application/application-status.jsx, src/renderer/marketplace/keyfi/checkout/keyfi-checkout-container.jsx, src/renderer/marketplace/keyfi/checkout/keyfi-checkout.jsx, stories/kyc.stories.js
Add a link to keyfi.com for completed kyc applications.
=> feat: add link to keyfi.com for approved applications

src/common/app/index.js, src/main/wallet/wallet-service.js, src/renderer/app.jsx, src/renderer/home/index.jsx, src/renderer/wallet/create/backup-hd-container.jsx, src/renderer/wallet/create/backup-hd.jsx, src/renderer/wallet/create/confirm-hd-container.jsx, src/renderer/wallet/create/confirm-hd.jsx, src/renderer/wallet/create/password/confirmation-container.jsx, src/renderer/wallet/create/password/password-component.jsx, src/renderer/wallet/create/password/password-util.js
use hd wallet flow for create wallet, instead of keystore
=> feat: create hd wallet

src/renderer/kyc/application/current-application-container.jsx, src/renderer/kyc/application/current-application-popup.jsx, src/renderer/marketplace/common/blocked-jurisdiction.jsx, src/renderer/marketplace/keyfi/checkout/keyfi-checkout-container.jsx, src/renderer/marketplace/keyfi/checkout/keyfi-checkout.jsx, stories/marketplace-common.stories.js
=> feat: disallow submissions from restricted jurisdictions

package.json, src/common/config.js
=> Release 1.9.0

src/renderer/dashboard/buy-key-popup-modal.jsx, src/renderer/dashboard/moonpay-agreement-modal.jsx, stories/buy-key.stories.js
=> 2500 moonpay terms

src/common/identity/reducers.js, src/common/moonpay/auth.js, src/main/moonpay/moonpay-service.js, src/main/moonpay/moonpay-service.spec.js, src/renderer/attributes/create-attribute-container.js, src/renderer/moonpay/auth-container.jsx, src/renderer/moonpay/auth-error-container.jsx, src/renderer/moonpay/auth-router.jsx, src/renderer/moonpay/moonpay-loading-container.jsx, src/renderer/moonpay/not-allowed-container.jsx, src/renderer/moonpay/not-allowed-modal.jsx, src/renderer/wallet/main/index.jsx, stories/buy-key.stories.js, yarn.lock
please review and merge #2512 first
Checks for service availability based on countries that moonpay supports https://support.moonpay.com/hc/en-gb/articles/360009279877-What-are-your-supported-countries-states-and-territories-.
If all countries of residece added to attributes and the ip country fail the this screen is shown:
=> 2499 service not available

src/renderer/moonpay/kyc-modal.jsx, src/renderer/moonpay/phone-verification-modal.jsx, stories/__fixtures__/kyc-requirements-moonpay.js, stories/buy-key.stories.js
please review and merge #2536 first
=> 2501 moonpay kyc ui

src/common/moonpay/payment.js
Fix missing state after card added.
=> fix: missing card added state

src/common/config.js, src/common/moonpay/auth.js, src/main/moonpay/moonpay-service.js, src/renderer/moonpay/country-not-allowed-container.jsx, src/renderer/moonpay/country-not-allowed-modal.jsx, src/renderer/wallet/main/index.jsx
- feat: moonpay release settings (removal of test settings)
- feat: improved blocked jurisdictions UI and error messages
=> feat: moonpay release settings

src/renderer/marketplace/passports/list/passports-list-table.jsx
=> feat: add investment type column

package.json, src/common/config.js, src/common/eth-gas-station/reducers.js, src/common/transaction/operations.js, src/common/transaction/operations.spec.js, src/common/transaction/reducers.js, src/common/transaction/selectors.js, src/common/transaction/types.js, src/common/wallet-connect/index.js, src/main/blockchain/eth-gas-station-service.js, src/main/wallet-connect/wallet-connect-service.js, src/main/wallet-connect/wallet-connect-sessions.js, src/main/wallet/wallet-service.js, src/renderer/common/accented-card.jsx, src/renderer/transaction/send/advanced-transaction.jsx, src/renderer/transaction/send/components/custom-transaction-settings.jsx, src/renderer/transaction/send/components/send-token-tab.jsx, src/renderer/transaction/send/components/transaction-fee-box.jsx, src/renderer/wallet-connect/sign-message-container.jsx, src/renderer/wallet-connect/transaction-component.jsx, src/renderer/wallet-connect/transaction-container.jsx, yarn.lock
=> feat: eip 1559 support

package.json, src/main/blockchain/web3-service.js, yarn.lock
=> fix: increase polling time for eth sync

src/common/contract/index.js, src/common/eth-gas-station/selectors.js, src/common/marketplace/orders/index.js, src/common/marketplaces/operations.js, src/common/marketplaces/selectors.js, src/main/blockchain/web3-service.js, src/renderer/did/create-did-popup-container.jsx, src/renderer/marketplace/bank-accounts/checkout/checkout-container.jsx, src/renderer/marketplace/common/payment-checkout.jsx, src/renderer/marketplace/incorporation/checkout/incorporations-checkout-container.jsx, src/renderer/marketplace/incorporation/checkout/incorporations-payment-container.jsx, src/renderer/marketplace/incorporation/list/incorporations-list-container.jsx, src/renderer/marketplace/keyfi/checkout/keyfi-checkout-container.jsx, src/renderer/marketplace/notarization/common/notaries-service-cost.jsx, src/renderer/marketplace/notarization/process/request-notarization-container.jsx, src/renderer/marketplace/orders/payment-container.jsx, src/renderer/marketplace/orders/payment.jsx, src/renderer/marketplace/passports/checkout/passports-checkout-container.jsx
=> feat: adds support for eip-1559 for marketplace orders

src/main/marketplace/inventory/inventory-service.js, src/renderer/did/create-did-popup-container.jsx, src/renderer/marketplace/bank-accounts/checkout/checkout-container.jsx, src/renderer/marketplace/incorporation/checkout/incorporations-checkout-container.jsx, src/renderer/marketplace/keyfi/checkout/keyfi-checkout-container.jsx, src/renderer/marketplace/notarization/process/request-notarization-container.jsx, src/renderer/marketplace/passports/checkout/passports-checkout-container.jsx
=> feat: check for gas station info data

src/common/contract/index.js, src/common/eth-gas-station/reducers.js, src/common/eth-gas-station/reducers.spec.js, src/common/eth-gas-station/selectors.js, src/common/marketplace/orders/index.js, src/common/marketplaces/marketplaces.spec.js, src/common/marketplaces/operations.js, src/common/marketplaces/selectors.js, src/common/transaction/operations.js, src/common/transaction/operations.spec.js, src/main/blockchain/eth-gas-station-service.js, src/main/token/price-service.js, src/renderer/did/create-did-popup-container.jsx, src/renderer/marketplace/bank-accounts/checkout/checkout-container.jsx, src/renderer/marketplace/incorporation/checkout/incorporations-checkout-container.jsx, src/renderer/marketplace/keyfi/checkout/keyfi-checkout-container.jsx, src/renderer/marketplace/notarization/process/request-notarization-container.jsx, src/renderer/marketplace/passports/checkout/passports-checkout-container.jsx, src/renderer/transaction/send/components/transaction-fee-box.jsx
=> fix: correct gas fee estimate url

src/common/transaction/operations.js, src/common/transaction/operations.spec.js, src/renderer/did/create-did-popup-container.jsx, src/renderer/marketplace/bank-accounts/checkout/checkout-container.jsx, src/renderer/marketplace/incorporation/checkout/incorporations-checkout-container.jsx, src/renderer/marketplace/keyfi/checkout/keyfi-checkout-container.jsx, src/renderer/marketplace/keyfi/widget/keyfi-widget.jsx, src/renderer/marketplace/notarization/process/request-notarization-container.jsx, src/renderer/marketplace/passports/checkout/passports-checkout-container.jsx, src/renderer/transaction/send/components/transaction-fee-box.jsx
=> 2636 fix pre defined gas calculation

src/main/blockchain/eth-gas-station-service.js, src/renderer/transaction/send/components/transaction-fee-box.jsx
=> fix: gas estimate fallback when api is unavailable
