src/main/controllers/cmc-service.js, src/main/controllers/models/token-price.js, src/main/controllers/sql-lite-service.js, src/main/migrations/20180508093508_init.js
I found out that the wallet was not running quickly enough on lower spec computers. 
So after some investigation I found out that the issue was regarding the Token Price Update into the SQlite db. I am changing it to bulk the insertion or update so it won't block the pool connection and other queries can run. 
Cheers
=> Fix performance issue when inserting and updating token prices

src/main/migrations/20180726210124_clear_token_price.js
fixes #324 
Removes old data from token prices.
Next time a price is updated, it will be without duplicates
This is a temporary fix, permanent solution will be tracked in #325
=> fix(token_price): duplicate tokens due to duplicate token price

src/common/kyc/index.js, src/renderer/kyc/application/current-application-container.jsx, src/renderer/marketplace/incorporation/common/program-price.jsx, src/renderer/marketplace/incorporation/detail/index.jsx, src/renderer/marketplace/incorporation/pay/checkout.jsx, src/renderer/marketplace/incorporation/pay/process-started.jsx
Some changes:
- Better handling of rpShouldUpdate, and session cache, differentiating between unauth and auth sessions
- Auth session is now triggered on click to "start incorporations" button
- User is redirected back if an existing application already exists.
- Should work with the hardware wallet flow.
=> feat: check for existing incorporation applications

src/common/transaction/operations.js, src/common/transaction/reducers.js, src/common/transaction/types.js, src/renderer/transaction/send/advanced-transaction.jsx, src/renderer/transaction/send/containers/transaction-fee-box.jsx
I've created a transaction attribute to indicate whether it's locked or not.
When the transaction is locked the Send button will be disabled
It can be used for any async operation to prevent users to send a transaction while this is being updated.
The transaction lock is used by:
- Gas price input change handler
- Gas limit input change handler
- setTransactionFee operation
I've also replaced some setTimeout's by a lodash debounce.
=> fix: disable send button while Network Transaction Fee is not calculated

src/common/transaction/selectors.js
fix for #1077 
It was converting the ethFee into crypto other than ETH, looks like the cryptoCurrency must be always ETH here.
=> fix: incorrect usd value of Network Transaction Fee

src/main/blockchain/tx-history-service.js, src/main/blockchain/tx-history.js, src/main/blockchain/web3-service.js, src/renderer/transaction/transactions-history/index.jsx
fix for #1102
I've updated the transaction history service. The old implementation was removing all pending transactions from the list, and also was not receiving updates from the blockchain. The user would have to hard reload the list to see new transactions.
The new implementation should:
* Keep pending transactions in the db
* Check all the pending transactions in the blockchain to receive updates
* Remove failed transactions from the db.
* I've also fixed a bug related to uppercase "from" and "to" attributes being saved into the db. It was breaking the search results.
=> fix: update transaction history to display sending status

src/renderer/marketplace/bank-accounts/list/account-type-tabs.jsx
Missing labels on account tabs for BAM.
Related to #1194
=> fix: BAM add missing labels for wealth manangement and corporate tabs

src/common/kyc/index.js
Prevents an error when going through all existing RPs to find open applications.
=> fix: handle empty rp config object

src/renderer/dashboard/token-box.jsx
=> fix: token box address long and font size

src/renderer/corporate/common/corporate-details.jsx
Previous fix to #1750 was not well thought.
It should find address by schema id instead of name.
=> fix: match by schema instead of label name

src/common/marketplace/orders/index.js, src/renderer/marketplace/bank-accounts/checkout/payment-complete-container.jsx, src/renderer/marketplace/bank-accounts/common/account-option.jsx, src/renderer/marketplace/bank-accounts/common/option-selection.jsx, src/renderer/marketplace/bank-accounts/index.jsx, src/renderer/marketplace/incorporation/checkout/incorporations-payment-complete-container.jsx, src/renderer/marketplace/incorporation/index.jsx
Fixes #1706.
Uses order instead of transaction model for processing marketplace payments.
Prevents error when navigating away from checkout flow in mid-process.
=> fix: get payment hash from order on marketplace transactions

src/common/identity/identity-duck.spec.js, src/common/identity/operations.js, src/common/identity/selectors.js
repeated calls to `selectIdentity(state)`  don't change after state change 
https://github.com/theKashey/kashe/issues/2
=> fix(selectors): replace keshe with reselect until cashe issues are fixed

src/renderer/marketplace/exchanges/exchanges-list-item.jsx
=> fix: removed left padding from fiat payment cells

src/renderer/corporate/member/corporate-member-container.jsx
=> fix: select correct parentId when editing an existing member

src/common/identity/operations.js, src/renderer/corporate/common/corporate-members.jsx, src/renderer/corporate/member/corporate-member-container.jsx
Fixes a number of issues:
- Update member error
- Adds missing email below member name in members screen
- Hides (for now) the invite user column
- Fixes issue with validation of equity
- Fixes issue with showing current member company as a possible parent when editing
=> fix: multiple corporate member fixes

src/renderer/corporate/common/corporate-shareholding.jsx
Adds a "unknown" data point to shareholder graph if total equity is below 100.
Fixes error reported on #1684
=> fix: tackle incomplete data points for shareholding graph

src/renderer/marketplace/bank-accounts/checkout/payment-complete-container.jsx, src/renderer/marketplace/bank-accounts/common/marketplace-bank-accounts-component.jsx, src/renderer/marketplace/bank-accounts/common/option-selection.jsx, src/renderer/marketplace/bank-accounts/select-bank/select-bank-container.jsx
- Fixes an edge case error in BAM bank selection if rp fails to load
- Disables continue button when application is still loading from RP
=> feat: loading message on select bank if waiting for RP

src/common/token-swap/index.js
Totle API stopped sending swap fees in some circumstances.
This fix handles that case.
=> fix: handle totle api response with no swap fee

.circleci/config.yml
Limits the number of workers in circle-ci jest unit test.
https://support.circleci.com/hc/en-us/articles/360038192673-NodeJS-Builds-or-Test-Suites-Fail-With-ENOMEM-or-a-Timeout
=> fix: failing circle ci unit tests with Error: spawn ENOMEM

src/renderer/transaction/common/transaction-error-box.jsx, src/renderer/transaction/transaction-no-gas-error/components/transaction-no-gas-error.jsx, yarn.lock
=> fix: remove static token in message displayed in transaction error popup

src/common/config.js, src/common/fiatCurrency/actions.js, src/common/fiatCurrency/operations.js, src/common/fiatCurrency/reducers.js, src/common/fiatCurrency/selectors.js, src/common/fiatCurrency/types.js, src/common/token-swap/index.js, src/main/context.js, src/main/currency/currency-service.js, src/renderer/marketplace/categories/categories-list.jsx, src/renderer/marketplace/loans/calculator/borrow-table.jsx, src/renderer/marketplace/loans/calculator/index.jsx, src/renderer/marketplace/loans/calculator/lend-table.jsx, src/renderer/marketplace/loans/common/calculator-card.jsx, src/renderer/marketplace/loans/common/filters.jsx, src/renderer/marketplace/loans/list/list-container.jsx, src/renderer/marketplace/loans/list/list-page.jsx, src/renderer/marketplace/marketplace-container.jsx
Addresses #2198 - displaying loan data in different currencies.
Gets fiat currency exchanges rates when needed from api.exchangeratesapi.io free service.
Allows loan calculations to be displayed in USD, EUR and GBP.
=> 2198 support multiple fiat currencies

src/renderer/marketplace/exchanges/exchanges-details.jsx, src/renderer/marketplace/loans/calculator/index.jsx, src/renderer/marketplace/loans/details/details.jsx
Addresses issues described on #2111
=> fix: support unlimited max loan term in calculator filters

.circleci/config.yml, appveyor.yml, package.json
- Commented out `gem install sass compass`, it's not needed and shouldn't be there, can be completely deleted.
- Increase no_output_timeout to 80m from 40 on circle-ci build-mac task
Please ignore the commit message referring to 1.6.1
=> Feat/release 1.6.0 mergeback

src/renderer/marketplace/bank-accounts/list/offers-table.jsx, src/renderer/marketplace/common/details-icon-button.jsx, src/renderer/marketplace/common/index.js, src/renderer/marketplace/exchanges/exchanges-list-item.jsx, src/renderer/marketplace/exchanges/exchanges-list.jsx, src/renderer/marketplace/incorporation/list/incorporations-list-table.jsx, src/renderer/marketplace/loans/calculator/borrow-table.jsx, src/renderer/marketplace/loans/calculator/lend-table.jsx, src/renderer/marketplace/loans/common/table.jsx
Changes:
- Changed `Details` (text) button to arrow icon in Marketplace tables (`Bank Accounts`, `Incorporation`, `Loans`, `Exchanges`)
From:
To:
=> 2334 marketplace details button

src/renderer/kyc/application/kyc-agreement-text.js
Do not render links if terms or privacy for vendor in airtable are empty
=> fix: remove link if empty in airtable

src/renderer/individual/dashboard/overview-tab.jsx
For users that already created a DID, show it in the selfkey profile.
=> fix: show existing DID if already created

src/renderer/marketplace/passports/details/passports-benefits-tab.jsx, src/renderer/marketplace/passports/details/passports-country-tab.jsx, src/renderer/marketplace/passports/details/passports-description-tab.jsx, src/renderer/marketplace/passports/details/passports-procedures-tab.jsx, src/renderer/marketplace/passports/details/passports-requirements-tab.jsx, src/renderer/marketplace/passports/details/passports-taxes-tab.jsx
Checks for missing data in passports program data.
=> Fix passports missing data check

src/common/config.js, src/main/token/token-service.js, src/renderer/wallet-connect/transaction-container.jsx
- Safe Gas Limit multiplier is now set at 1.5 (same as metamask)
- Multiplier is now configured via env var SAFE_GAS_MULTIPLIER
=> feat: updated safe gas multiplier

src/common/app/index.js
=> fix: prevent export when keystore is unavailable
